#!/bin/sh

REPO="https://github.com/dabigblob/ani-cli.git"

case "$(uname -o)" in
    Android*)
        ins_base="/data/data/com.termux/files/usr"
        ;;
    *)
        printf "This uninstaller is only for Android. Bye."
        exit 1
        ;;
esac

if [ -d "${ins_base}/share" ] || [ -d "${ins_base}/bin" ]; then
    mkdir -p "${ins_base}/share" "${ins_base}/bin"
fi

rm -rf "${ins_base}/share/ani-cli" "${ins_base}/bin/ani-cli"

git clone -b "master" "$REPO" "${ins_base}/share/ani-cli"

ln -sf "${ins_base}/share/ani-cli/ani-cli" "${ins_base}/bin/ani-cli"

exit 0
