#!/bin/sh

case "$(uname -o)" in
    Android*)
        ins_base="/data/data/com.termux/files/usr"
        ;;
    *)
        printf "This uninstaller is only for Android. Bye."
        exit 1
        ;;
esac

rm -rf "${ins_base}/share/ani-cli" "${ins_base}/bin/ani-cli"

exit 0
