#!/bin/sh

REPO="https://github.com/dabigblob/ani-cli.git"

case "$(uname)" in
    Darwin*)
        ins_base="$(brew --prefix)"
        ;;
    Linux*)
        case "$(uname -o)" in
            Android*)
                ins_base="/data/data/com.termux/files/usr"
                ;;
            *)
                #we're not considering non-GNU systems here as the -o flag is gnu coreutil specific
                ins_base="/usr/local"
                ;;
        esac
        ;;
    MINGW64*)
        ins_base="/usr/local"
        ;;
    *)
        printf "This uninstaller is only for Windows, Android, Linux and MacOS. Bye."
        exit 1
        ;;
esac

mkdir -p "${ins_base}/share" "${ins_base}/bin"

rm -rf "${ins_base}/share/ani-cli" "${ins_base}/bin/ani-cli"

git clone -b "master" "$REPO" "${ins_base}/share/ani-cli"

ln -sf "${ins_base}/share/ani-cli/ani-cli" "${ins_base}/bin/ani-cli"

exit 0
